---
- hosts: all
  become: yes
  tasks:
   - name: install webserver on ubuntu
     apt:
      name:
      state: present
     when: ansible_os_family =="Debian" 

   - name: start webserver on ubuntu
     service:
      name: apache2
      state: started
     when: ansible_os_family =="Debian" 

   - name: install webserver on amazon
     yum:
       name:
        state: present
     when: ansible_os_family =="RedHat"
   
   - name: install webserver on amazon
     service:
      name: httpd
      state: started
     when: ansible_os_family =="RedHat"    
