---
- hosts: all
  become: yes
  tasks:
  - name: install webserver on ubuntu
    apt:  
     name: "{{ webserveronUbuntu }}"
     state: present
    when: ansible_os_family =="Debian" 

  - name: start webserver on ubuntu
    service:
     name: "{{ webserveronUbuntu }}"
     state: started
    when: ansible_os_family =="Debian" 

  - name: install webserver on amazon
    yum:
     name: "{{ webserveronamazon }}"
     state: present
    when: ansible_os_family =="RedHat"
   
  - name: install webserver on amazon
    service:
     name: "{{ webserveronamazon }}"
     state: started
    when: ansible_os_family =="RedHat"    
