---
- hosts: all
  become: yes
  tasks:
   - name: install webserver
     apt: 
      name: apache2
      state: present
     when: ansible_os_family =="RedHat" 

   - name: start webserver
     service: 
      name: apache2
      state: started    
     when: ansible_os_family == "RedHat" 